version: '3.9'
services:
  server:
    build:
      context: .
      # dockerfile: Dockerfile
      target: Builder
    volumes:
      - server_node_modules:/server/node_modules
      - client_node_modules:/client/node_modules
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - mongodb
    networks:
      - tribe
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - tribe
    volumes:
      - db:/data/db
    restart: unless-stopped

volumes:
  client_node_modules:
  server_node_modules:
  db:
networks:
  tribe:
    driver: bridge
