version: '3.9'
services:
  server:
    build:
      context: .
      target: Builder
    volumes:
      - server_node_modules:./server/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - tribe
    restart: unless-stopped
  client:
    build:
      context: .
      target: Runner
    volumes:
      - client_node_modules:./client/node_modules
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - tribe
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    ports:
      - 27014:27017
    networks:
      - tribe
    volumes:
      - db:/data/db
    restart: unless-stopped

volumes:
  client_node_modules:
  server_node_modules:
  db:
networks:
  tribe:
    driver: bridge
